In [1]:
!pip install nptyping beartype

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     --------------------------------- ------ 51.2/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/917.8 kB ? eta -:--:--
   --- ------------------------------------ 81.9/917.8 kB 2.3 MB/s eta 0:00:01
   ---- ----------------------------------- 112.6/917.8 kB 1.1 MB/s eta 0:00:01
   ------- -------------------------------- 163.8/917.8 kB 1.2 MB/s eta 0:00:01
   -------- ------------------------------- 204.8/917.8 kB 1.0 MB/s eta 0:00:01
   ---------- ----------------------------- 245.8/917.8 kB 1.0 MB/s eta 0:00:01
   ----------- -------------------------- 286.7/917.8 kB 983.9 kB/s eta 0:00:01
   ----------- -------------------------- 286.7/917.8 kB 983.9 kB/s eta 0:00:01
   ------------ ------------------------- 307.2/917.8 kB 827.2 kB/s eta 0:00:01
   ------------- ------------------------ 337.9/917.8 kB 807.1 kB

## Scalar Value

In [1]:
import numpy as np

a : np.ndarray = np.array(1000) # this is a numpy Object to store, ndarray is numpy class, & we have to look into its basic properties , this 1000 or any other single number is scalar and scalar has no dimension

display(a) # print
display(a.shape) # prints the shape of object () = 0 - Dimension
display(a.dtype) # print the data typpe of the Object 
display(type(a)) # prints 
display(a.ndim) # print the number of the dimensions
display(a.size) # print the size of the object, size tells about number of items in any array 
display(a.itemsize) # print the item size of the object , how many bits it is stored in

# these are basic properties we check on data 

array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

## Vector Type

In [4]:

a : np.ndarray = np.array([1, 2, 3, 4]) # this is a vector type, values stored in a list with one dimension

display(f" {a}") # print
display(f" Object shape {a.shape}") # prints the shape of object () = 0 - Dimension (means axis)
display(f" Object data type {a.dtype}") # print the data typpe of the Object 
display(f" Global object type with global function {type(a)} ") # prints 
display(f" Number of Dimension {a.ndim}") # print the number of the dimensions
display(f" Total items in array {a.size}") # print the size of the object, size tells about number of items in any array 
display(a.itemsize) # print the item size of the object , how many bits it is stored in

' [1 2 3 4]'

' Object shape (4,)'

' Object data type int32'

" Global object type with global function <class 'numpy.ndarray'> "

' Number of Dimension 1'

' Total items in array 4'

4

In [ ]:
help(a.itemsize)

## Matrix

In [10]:
import numpy as np
data = [[1, 2, 3, 4],  # 2d array, we ahave 3 rows and 4 columns, we have a matrix with 3 rows and 4 column
        [5, 6, 7, 8],
        [9, 10, 11, 12]]


a : np.ndarray = np.array(data) # this is a vector type, values stored in a list with one dimension

display(f" {a}") # print
display(f" Object shape {a.shape}") # prints the shape of object (2) = 2 - Dimension (means axis)
display(f" Object data type {a.dtype}") # print the data typpe of the Object 
display(f" Global object type with global function {type(a)} ") # prints 
display(f" Number of Dimension {a.ndim}") # print the number of the dimensions
display(f" Total items in array {a.size}") # print the size of the object, size tells about number of items in any array 
display(a.itemsize) # print the item size of the object , how many bits it is stored in

' [[ 1  2  3  4]\n [ 5  6  7  8]\n [ 9 10 11 12]]'

' Object shape (3, 4)'

' Object data type int32'

" Global object type with global function <class 'numpy.ndarray'> "

' Number of Dimension 2'

' Total items in array 12'

4

### why Numpy?
Numpy has made as in real world we have dimensions goes till 5 D as stored video has 5 dimenions, RGB image is of 3 dimension and have dimesion more than 5 in a fast way we use Numpy to handle.

* Above we have practiced through old way, proceeding we will be practising new ways.

## Numpy with NDArray typing Support

In [15]:
# we have to make an array

from nptyping import NDArray, Shape, UInt64
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1 ,11) # here data is a variable with type NDArray , then defining shape means making a matrix with number of items as 10, unsigned Integer thi is data 
                                    # if we want to generate range.


data # a 1 dimensional array has been generated 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# matrix of any dimension means 1D, 2D, 5D manipulation on it as if we say + 5 in evrey value

from nptyping import NDArray, Shape, UInt64
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1 ,11)

data + 5 # this can not be done through list with + operator directly between 2 operands

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Time calculation with numpy & list

In [21]:
%%time
data : NDArray [Shape["10"] , Any ] = np.arange(1, 10000000)
data + 5


CPU times: total: 31.2 ms
Wall time: 50.9 ms


array([       6,        7,        8, ..., 10000002, 10000003, 10000004])

In [22]:
%%time
data : list[int] = list(range(1, 10000000))
[i + 5 for i in data ]

CPU times: total: 1.27 s
Wall time: 1.44 s


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


## Numpy advance Operations vs list Opreations

In [24]:
# list
data : list[int] = list (range (1,21))
print(data)
print(data[5:11]) 
data[5:11] = 1000  # bt if we want to update this slicing value, which list dont allow to update all sliced values by 1000
print(data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [28]:
# Numpy array
ndata : NDArray[Shape["20"], Any] = np.arange(1, 21) # called function with 1-21
print(ndata)
print(ndata[5: 11])
ndata[5:11] = 1000 # updating data, Example being done at backend of adobe through slicing whenwe are fixing blur eyes stc
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


In [ ]:
# Converting array to numpy image : task

# Numpy 1d Functions

In [32]:
state_bank : NDArray[Shape["10"], Any] = np.array([1, 5, 7, 12]) # with np function we can convert any tuple, set, lsit can be convert to an Array, from range fixed numbers generte

ubl_bank : NDArray[Shape["100"], Any] = np.random.randint(1,100, 20)   # here we use , with randint we can tell high and low numbers adn its types
                                                                # set here boundry of min and max number and specified number of items to be generated 

display(state_bank)
display(ubl_bank)


array([ 1,  5,  7, 12])

array([70, 47, 80, 81, 27, 19, 63, 67, 56, 14, 13, 68, 92, 79, 75, 71, 24,
       94, 54, 39])

### Boolean Slicing 

In [35]:
# Boolean Slicing : Topic for Slicing in Numpy
from nptyping import Bool 
state_bank : NDArray[Shape["10"], Any] = np.array([1, 5, 7, 12])
# [1,       5,    7,    12] #according to rule it is must to have every index same dimension, this array is one dimension with 4 index, rhen boolean slicer should also have same dimension and number of item
# [True,  False, false, true]
# variable [True,  False, false, true], it will return where ever have true values 

select : NDArray[Shape["10"], Bool]= np.array([True,  False, False, True])
state_bank[select]


array([ 1, 12])

In [36]:
# making Boolean Array Method 2 
state_bank : NDArray[Shape["10"], Any] = np.array([1, 5, 7, 12])
state_bank % 2 == 2

array([False, False, False, False])

In [38]:
state_bank : NDArray[Shape["10"], Any] = np.array([1, 5, 7, 12])
state_bank[state_bank % 2 == 2]

array([], dtype=int32)

In [44]:
display(state_bank)
display(ubl_bank)
#        4 Items     search 20 Items
state_bank[np.in1d(state_bank,ubl_bank)]# first varibale item length returned 

array([ 1,  5,  7, 12])

array([70, 47, 80, 81, 27, 19, 63, 67, 56, 14, 13, 68, 92, 79, 75, 71, 24,
       94, 54, 39])

array([], dtype=int32)

In [45]:
np.intersect1d(state_bank,ubl_bank) # for unions and diagrams

array([], dtype=int32)

In [49]:
# performing the comparison, needed for comparison between matrices 
x : NDArray[Shape["5"],Any ] = np.array([1, 3, 4, 5, 7])
y : NDArray[Shape["5"],Any ] = np.array([6, 3, 2, 5, 7, 100])
display(x)
display(y)
np.where(x > y, x, y)


array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5,   7, 100])

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

# Create Numpy Arrays

In [51]:
a : NDArray [Shape["*, *"], Any] = np.array([[1, 2, 3], # * means same, can be any rows and columns
                                                       [4, 5, 6]])

print(a)

b : NDArray [Shape["Size, Size"], Any] = np.array([[1, 2, ],
                                                       [4, 5, ]])
print(b)

c : NDArray [Shape["Size, Size"], Any] = np.array([["A" ],
                                                       ["B" ]])
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [52]:
np.who() # displayed in table all variables made with details

Name            Shape            Bytes            Type

_               0                0                int32
__              0                0                int32
___             4                4                bool
a               2 x 3            24               int32
_15             10               40               int32
_16             10               40               int32
_18             999999           3999996          int32
_21             9999999          39999996         int32
ndata           20               80               int32
state_bank      4                16               int32
ubl_bank        20               80               int32
select          4                4                bool
_35             2                8                int32
_36             4                4                bool
_38             0                0                int32
_42 (___)       4                4                bool
_44 (__)        0                0                in

In [ ]:
# When we save data it saves as py file, we can save dat ain numpy, pickle, h5 and figure, csv converts into text there are different file types with different extensions like csv and have different python best packages available to manage those
# Polaris is faster than Pandas. StremeLit, flask ui,
# if we have developed a tool and want to make it part of website or connect module type, can we make it part of mobile app, 
# if we want paython app we have kivi package for desktop app pycutie5 app, also web application in pure python (if we dont knowhtml css, react, jS) we have "streamlit" which we will learn in this course 
#  we can make quick application, to help see client this is web we have uploaded pirctures  adn can display result on web, but for
# advance product as we are expect of Next, TS and react we use Next Js and made Flask API and get it integrated usage is tat the UI and UX will also be standard + on backend ew can use flash API
# or Django API weather rest of Graph QL we can connect . MAin thing is making end to end application .
#        

# Creating any dimension Arrray  

In [ ]:
# in Numpy slicing matters , we will be making array dimesnion of any lenght 


In [53]:
# one Dimensinal array

a : NDArray [Shape["Size, Size"], Any] = np.arange(1,5)
print(a)
a : NDArray [Shape["Size, Size"], Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [54]:
# Two Dimneional Array

a : NDArray [Shape["Size, Size"], Any] = np.arange(3 * 3).reshape (3,3) # np. range returned as an Object 
print(a)
a : NDArray [Shape["Size, Size"], Any] = np.arange(5*3).reshape(5,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [56]:
        

a : NDArray [Shape["Size, Size"], Any] = np.arange(3 * 3).reshape (3,3) # np. range returned as an Object 
print(a)
print('============================')
a : NDArray [Shape["Size, Size"], Any] = np.arange(5*2*2).reshape(5,2,2) # 5 picture of 2*2
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [59]:
#   as many dimension we have , we can pass as many clicing indexes 

a : NDArray [Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape (5,2,2) # np. range returned as an Object 
a[::2,::,::] # as many  picks one leaves other 

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [ ]:
a : NDArray [Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape (5,2,2) # np. range returned as an Object 
a[a% == 2] # even number from this matrics 

In [60]:
np.asarray([1, 2, 3])

array([1, 2, 3])

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [63]:
np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
# we can pass indexing by our own way 
a : NDArray [Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape (5,2,2)
a[[0,-1],::,::]

In [66]:
a : NDArray [Shape["20"], Any] = np.arange(1*21)
print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax())
print(ndata.argmin())
print(ndata.mean())
print(ndata.std())
print(ndata.sum())
print(ndata.cumsum())


[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]
1
1000
5
